<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="BGLRT49500328" name="com.qa.TestScripts.TC13_Emp_Details" tests="3" failures="0" timestamp="19 Nov 2021 10:01:03 GMT" time="18.819" errors="1">
  <testcase name="Screenshot" time="0.433" classname="com.qa.TestScripts.TC13_Emp_Details">
    <error type="java.io.IOException" message="Destination &#039;C:\Users\kovvuria\Documents\Selenium\com.qa.selenium.Batch1.Assignments\test-output&#039; directory cannot be created">
      <![CDATA[java.io.IOException: Destination 'C:\Users\kovvuria\Documents\Selenium\com.qa.selenium.Batch1.Assignments\test-output' directory cannot be created
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:879)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:835)
	at org.apache.commons.io.FileUtils.copyFile(FileUtils.java:802)
	at com.qa.TestScripts.TC13_Emp_Details.takeSnapShot(TC13_Emp_Details.java:87)
	at com.qa.TestScripts.TC13_Emp_Details.Screenshot(TC13_Emp_Details.java:63)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:646)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:811)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1137)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:753)
	at org.testng.TestRunner.run(TestRunner.java:607)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:368)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:363)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:321)
	at org.testng.SuiteRunner.run(SuiteRunner.java:270)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1284)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1209)
	at org.testng.TestNG.runSuites(TestNG.java:1124)
	at org.testng.TestNG.run(TestNG.java:1096)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </error>
  </testcase> <!-- Screenshot -->
  <testcase name="Search" time="9.438" classname="com.qa.TestScripts.TC13_Emp_Details"/>
  <testcase name="Login" time="8.948" classname="com.qa.TestScripts.TC13_Emp_Details"/>
</testsuite> <!-- com.qa.TestScripts.TC13_Emp_Details -->
